services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ppl\PplDeeplV3Requests\:
    resource: '../Classes/*'

  Ppl\PplDeeplV3Requests\Service\DeeplApiClientService:
    public: true

  Ppl\PplDeeplV3Requests\Service\DeeplConfigurationService:
    public: true

  Ppl\PplDeeplV3Requests\Service\DeeplLanguageConfigurationService:
    public: true

  Ppl\PplDeeplV3Requests\Service\DeeplGlossaryConfigurationService:
    public: true

  Ppl\PplDeeplV3Requests\Service\DeeplStyleRuleConfigurationService:
    public: true

  Ppl\PplDeeplV3Requests\Service\DeeplCustomInstructionConfigurationService:
    public: true
